language: php
php:
  - '5.5'
  - '5.4'
  - '5.3'
  - hhvm
before_install:
  - chmod +x configure.sh
  - sh configure.sh
install:
  - mysql -e 'drop database if exists bakaigniter;'
  - mysql -e 'create database bakaigniter;'
  - mysql -utravis bakaigniter < database.sql
script:
  - phpunit
matrix:
  fast_finish: true
branches:
  only:
    - master
